### ISSUE TITLE
Debian 8 chef_12.8.1-1 fails to install

### ISSUE THREAD

**Issue by dhoer** [chef/omnitruck#173]
See https://travis-ci.org/dhoer/chef-flywaydb/jobs/121483156#L728 for more details.  

This worked in the previous build with no issues and I haven't changed anything that would affect this: https://travis-ci.org/dhoer/chef-flywaydb/jobs/118589500#L739.

**Comment by dhoer** [comment]
I went ahead and removed support for debian.  So you can close this if you want.

**Comment by efpe** [comment]
Hello,

The same here. I would like to build a container image with preinstalled chef-client. I use Packer and docker-machine to build the image. The problem only appears when using debian:jessie (for example with ubuntu:14.04 it works like a charm).

After a few minutes it turned out that a lot of certificates were removed from the ca-certificates package in Debian. You can find the bugreport here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812708.

**Comment by jaybrueder** [comment]
I experienced the same when using Packer or trying to converge with Test-Kitchen.

Works like a charm with anything but debian:jessie.

**Comment by schisamo** [comment]
This should be fixed by https://github.com/chef/mixlib-install/pull/103, we just need to update the version of mixlib-install that Omnitruck is pinned to. /cc @sersut

**Comment by sersut** [comment]
This should be fixed now. Let us know if this issue still reproes.
