### ISSUE TITLE
Try to install chef-solo on Ubuntu Precise via a VirtualBox VM and Vagrant

### ISSUE THREAD

**Issue by MantaRayDeeJay** [chef/omnitruck#187]
vagrant@precise64:/vagrant$ sudo curl -L https://www.opscode.com/chef/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19831  100 19831    0     0  11476      0  0:00:01  0:00:01 --:--:-- 21720
ubuntu 12.04 x86_64
Getting information for chef stable  for ubuntu...
downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=12.04&m=x86_64
  to file /tmp/install.sh.1475/metadata.txt
trying wget...
sha1    bc4a6642d6093b54de856da31f0651a56b0fdc8e
sha256  f1cf5d0f6dd12d2d2296ec6d8dbb16363f8541f5c15298cafa70e65ff2b5a22f
url     https://packages.chef.io/stable/ubuntu/12.04/chef_12.11.18-1_amd64.deb
version 12.11.18
downloaded metadata file looks valid...
downloading https://packages.chef.io/stable/ubuntu/12.04/chef_12.11.18-1_amd64.deb
  to file /tmp/install.sh.1475/chef_12.11.18-1_amd64.deb
trying wget...
trying curl...
Comparing checksum with sha256sum...

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

You are installing an omnibus package without a version pin.  If you are installing
on production servers via an automated process this is DANGEROUS and you will
be upgraded without warning on new releases, even to new major releases.
Letting the version float is only appropriate in desktop, test, development or
CI/CD environments.

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

Installing chef
installing with dpkg...
dpkg: error: requested operation requires superuser privilege
Installation failed
Version:

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.

In this case, you need to run bash with sudo, not curl:
`curl ... | sudo bash`.

Thanks,
-Thom

**Comment by MantaRayDeeJay** [comment]
Thanks Thom for your answer.
I'm a newbie here, and I didn't well understand this way to ask some help.
Now, I know that this place is only for issues and feature request.

Regards
