### ISSUE TITLE
Installing Chef 11.6.0-1 on MacOS X 10.11.5

### ISSUE THREAD

**Issue by flaschbier** [chef/omnitruck#189]
As requested by the installation procedure:

```
ln: /usr/bin/chef-client: Operation not permitted
makeselfinst: Cannot link chef-client to /usr/bin
Installation failed
Version: 11.6.0-1

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
```
done

```
Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.
```

Corporate requirement is to use Chef 11.6.0-1, so I did:
```
curl -L https://www.opscode.com/chef/install.sh | sudo -E bash -s -- -v 11.6.0-1
```
Running under MacOS X 10.11.5 in a bash.

Remark: Not fully unexpected, the same happens when I download from https://packages.chef.io/stable/mac_os_x/10.7/chef-11.6.0_1.mac_os_x.10.7.2.sh and then
```
sudo bash chef-11.6.0_1.mac_os_x.10.7.2.sh
```

**Comment by thommay** [comment]
This is not the correct repository, but we're not likely to ever fix this - basically, OS X added SIP in El Capitan - https://support.apple.com/en-gb/HT204899 - and the old chef packages attempt to write to a SIP protected path. 
If you need such an old version of chef to support your cookbooks, I'd strongly recommend that you use test-kitchen to install a virtual machine and an old chef version. Otherwise, you'll need to install chef manually using ruby gems.
